#! /bin/sh

# **********************************************************************************************************************
# Daemon configuration
# **********************************************************************************************************************

DAEMON_NAME="led-daemon"
DAEMON_JAR="/build-tv/led-daemon.jar"
DAEMON_WORKING_DIR="/build-tv"
DAEMON_USER="root"

# **********************************************************************************************************************
# Main
# **********************************************************************************************************************

start()
{
    echo "Starting ${DAEMON_NAME} ..."

    start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/${DAEMON_NAME}.pid \
                --background \
                --chdir ${DAEMON_WORKING_DIR} \
                --chuid "${DAEMON_USER}" \
                --exec /usr/bin/java -- -jar ${DAEMON_JAR}
}

stop()
{
    echo "Stopping ${DAEMON_NAME} ..."

    start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/${DAEMON_NAME}.pid
}

test()
{
    exec /usr/bin/java -jar "${DAEMON_JAR}" test
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 5
        start
        ;;
    test)
        test
        ;;
    *)
        echo "Usage: /etc/init.d/${DAEMON_NAME} {start|stop|restart|test}"
        exit 1
        ;;
esac

exit 0
