# LED daemon settings
led-daemon.leds=59
led-daemon.pin=18
led-daemon.freq=800000
led-daemon.dma=5
led-daemon.brightness=255
led-daemon.pwm_channel=0
led-daemon.invert=false

# LED daemon REST API settings
led-daemon.rest.port=2500

# Jenkins status service settings
jenkins.base=https://builds.apache.org/view/All/job/
jenkins.jobs=ZooKeeper_branch35_jdk7,maven-plugins-ITs-m2
jenkins.poll-rate-ms=10000

# LED daemon endpoint settings
led-daemon.url=http://localhost:2500

